### ISSUE TITLE
Compilation error.

### ISSUE THREAD

**Issue by Krot666** [EnergyCoinProject/energycoin#1]
When you run the **qmake** command, the script for creating a new file does not work.

*** Error in `g++': double free or corruption (top): 0x01a8f148 ***
Makefile:673: failed to perform the recipe for the target «build/txdb.o»
make: *** [build/txdb.o] Emergency Stop

**Comment by MicicFilip** [comment]
@Krot666 did you try running just **make** command?

**Comment by Krot666** [comment]
Yes, the **make** used on two cores.
![screenshot_2](https://user-images.githubusercontent.com/33595988/42861352-d74f4748-8a84-11e8-8d0b-e04e84ed4fff.png)

**Comment by Krot666** [comment]
I found one mistake.
In file **makefile.unix**
http://prntscr.com/k7udj7

**Comment by Krot666** [comment]
I think the compilation error is related to the GCC version.
I have: gcc (Raspbian 4.9.2-10+deb8u1) 4.9.2 

You must update the source files to newer versions.
Otherwise on Rapsberry Pi 3, it will be impossible to launch a purse.
And versions 1 and 2 have long been outdated and do not use them.

**Comment by MicicFilip** [comment]
Hey @Krot666, try updating your gcc to this version: gcc version 5.4.0 20160609

**Comment by Krot666** [comment]
It's all useless (
I installed the last Scratch.
Now such errors:
http://prntscr.com/k8sekk

This parameter specifies which set of processor instructions to generate.
As far as I know, this is a set of instructions for Intel's processor Sendi Bridge.

**Mikefile** absolutely does not fit, most likely it's out of date for 4 years and you need to recheck all the code.

**Comment by MicicFilip** [comment]
@Krot666 What OS do you use? I want to try and reproduce the problem

**Comment by Krot666** [comment]
Both Jesse in 2014, and the latest Scratch ... from the Rapsberry site.

**Comment by Krot666** [comment]
At this point the whole process ends. I have no ideas(
![screenshot_2](https://user-images.githubusercontent.com/33595988/43042362-df1c0a5a-8da5-11e8-851d-5f903b8ee80c.png)

**Comment by Krot666** [comment]
Any news?

**Comment by Krot666** [comment]
Hey???
